version: '3'
services:
  sharkauction-backend:
    image: phuctth/sharkauction:latest
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db_sharkauction
      MYSQL_PORT: 3306
      MYSQL_USER: phuctth
      MYSQL_PASSWORD: EXE201
      MYSQL_DATABASE: sharkauction
    depends_on:
      - db_sharkauction


  db_sharkauction:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: EXE201
      MYSQL_DATABASE: sharkauction
      MYSQL_USER: phuctth
      MYSQL_PASSWORD: EXE201
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
