server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:sharkauction}?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: Asia/Ho_Chi_Minh
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jackson:
    time-zone: Asia/Ho_Chi_Minh
app:
  fe:
    verify_url: ${VERIFY_URL:http://128.199.193.209:8080/api/v1/user/verify}
    forgot_password_url: ${FORGOT_PASSWORD_URL:http://128.199.193.209:8080/api/v1/user/setpassword}
  cors:
    allowedOrigins: http://localhost:4176,http://localhost:4200,http://localhost:4201,http://localhost:5173,http://localhost:5100,http://localhost:${SERVER_PORT:8080},http://128.199.193.209:${SERVER_PORT:8080}
  api:
    version:
      v1: /api/v1
  openapi:
    dev-url: http://localhost:${SERVER_PORT:8080}
    prod-url: http://128.199.193.209:8080
  auth:
    tokenSecret: T04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    refreshTokenExpirationMsec: 864000000  # 10 days
    accessTokenExpirationMsec: 1800000 # 15 minutes
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL:sharkauctioncompany@gmail.com}
    password: ${EMAIL_PASSWORD:ascn dywm bilk jsra}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
